# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Utility to build and distribute the TimeManagementUI examples app"

  lane :build_examples do
	build_ios_app(scheme: "TimeManagementUIExamples", project: "TimeManagementUIExamples.xcodeproj")
	
	appcenter_upload(
		api_token: ENV["APP_CENTER_TOKEN"],
  		owner_name: "maierj",
  		app_name: "TimeManagementUI-Examples",
  		file: ""
	)		
  end
end
